export const uploadSchema = [
  'CREATE TABLE IF NOT EXISTS archive_imports(id TEXT PRIMARY KEY,phase TEXT NOT NULL,chain TEXT NOT NULL,events INTEGER NOT NULL,expected INTEGER NOT NULL,last_tick INTEGER NOT NULL,state_bytes INTEGER NOT NULL,entities TEXT)',

  'CREATE TABLE IF NOT EXISTS uploads(id TEXT PRIMARY KEY,member TEXT NOT NULL,epoch TEXT NOT NULL,hash TEXT NOT NULL,bytes INTEGER NOT NULL,received INTEGER NOT NULL DEFAULT 0,next INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL,expires INTEGER NOT NULL,summary TEXT,validation_until INTEGER NOT NULL DEFAULT 0)',
  'CREATE TABLE IF NOT EXISTS upload_parts(upload TEXT NOT NULL,part INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(upload,part))',
  'CREATE TABLE IF NOT EXISTS upload_states(upload TEXT NOT NULL,part INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(upload,part))',
  'CREATE TABLE IF NOT EXISTS upload_events(upload TEXT NOT NULL,seq INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(upload,seq))',
  "CREATE UNIQUE INDEX IF NOT EXISTS upload_events_id ON upload_events(upload,json_extract(body,'$.id'))",
];
export const replaySchema = [
  'CREATE TABLE IF NOT EXISTS replay_session(id INTEGER PRIMARY KEY CHECK(id=1),epoch TEXT NOT NULL,revision INTEGER NOT NULL,head INTEGER NOT NULL,bytes INTEGER NOT NULL,status TEXT NOT NULL,created INTEGER NOT NULL,build TEXT NOT NULL,hash TEXT NOT NULL)',
  'CREATE TABLE IF NOT EXISTS replay_parts(frame INTEGER NOT NULL,part INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(frame,part))',
];
export const expressionSchema = [
  'CREATE TABLE IF NOT EXISTS expressions(id TEXT PRIMARY KEY,member TEXT NOT NULL,epoch TEXT NOT NULL,generation TEXT NOT NULL,mode TEXT NOT NULL,context TEXT NOT NULL,token TEXT NOT NULL,expires INTEGER NOT NULL,created INTEGER NOT NULL,status TEXT NOT NULL,result TEXT)',
];

export const continuitySchema = [
  'CREATE TABLE IF NOT EXISTS engine_recovery_failures(id TEXT PRIMARY KEY,source TEXT NOT NULL,target TEXT NOT NULL,epoch TEXT NOT NULL,revision INTEGER NOT NULL,ticks INTEGER NOT NULL,code TEXT NOT NULL,created INTEGER NOT NULL)',
  'CREATE TABLE IF NOT EXISTS operation_storage(epoch TEXT PRIMARY KEY,seq INTEGER NOT NULL,bytes INTEGER NOT NULL)',
  'CREATE TABLE IF NOT EXISTS engine_migrations(id TEXT PRIMARY KEY,source TEXT NOT NULL,target TEXT NOT NULL,epoch TEXT NOT NULL,ticks INTEGER NOT NULL,events INTEGER NOT NULL,created INTEGER NOT NULL)',
  'CREATE TABLE IF NOT EXISTS operation_batches(id TEXT PRIMARY KEY,day TEXT NOT NULL)',
  'CREATE TABLE IF NOT EXISTS operation_days(day TEXT PRIMARY KEY,requests INTEGER NOT NULL,errors INTEGER NOT NULL,total_ms INTEGER NOT NULL,max_ms INTEGER NOT NULL,slow INTEGER NOT NULL,epoch TEXT NOT NULL,revision INTEGER NOT NULL,tick INTEGER NOT NULL,events INTEGER NOT NULL,state_bytes INTEGER NOT NULL,archive_bytes INTEGER NOT NULL,measured INTEGER NOT NULL)',
];
