import { heritageView } from './heritage';
import { urbanView, citizenView } from './urban';
import { type WorldState, type NPC, DAYS_PER_YEAR } from '../sim/types';
import { stocks, market, capacity } from '../sim/civilization';
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export function familyView(w: WorldState, n: NPC) {
  const person = (id: string) => { const p = w.npcs.find(n => n.id === id); return p ? `<button class="text-button" data-npc="${esc(id)}">${esc(p.identity.name)}${p.alive ? '' : ' †'}</button>` : ''; };
  const children = w.npcs.filter(p => p.life?.parentIds.includes(n.id));
  return citizenView(w, n) + `<button id="family-tree" class="button">가계도와 계승 기록</button><div class="family-card"><div class="section-label">가족과 계승 <span>${n.life.generation}세대 · ${n.identity.age < 18 ? '성장기' : n.identity.age >= 65 ? '노년기' : '성인'}</span></div><p>부모: ${n.life.parentIds.map(person).join(' · ') || (n.profile ? '입주 이전 가족 기록 없음' : '초기 정착민')}<br>배우자: ${n.life.partnerId ? person(n.life.partnerId) : '없음'}<br>자녀: ${children.map(c => person(c.id)).join(' · ') || '없음'}</p><p>${esc(w.civilization.settlements.find(v => v.id === n.settlementId)?.name ?? '')} · 생활 기술 ${n.life.skill.toFixed(1)}<br>소유 주택 ${w.buildings.filter(b => b.ownerIds?.includes(n.id)).length}채 · 게임 ${DAYS_PER_YEAR}일 = 1년</p>${n.life.birthEventId ? `<button class="evidence-link" data-event="${esc(n.life.birthEventId)}">출생 사건 보기</button>` : ''}${n.life.deathEventId ? `<button class="evidence-link" data-event="${esc(n.life.deathEventId)}">사망·상속 원인 보기</button>` : ''}</div>`;
}
export function civilizationView(w: WorldState) {
  const c = w.civilization;
  return `<div class="civilization-heading"><h3>마을과 세대</h3><span>${c.settlements.length}개 마을 · ${w.npcs.filter(n => n.alive && n.identity.age < 18).length}명 성장 중 · ${Math.max(...w.npcs.map(n => n.life.generation))}세대</span></div><div class="settlement-list">${c.settlements.map(v => {
    const people = w.npcs.filter(n => n.alive && n.settlementId === v.id), stock = stocks(w, v.id), m = market(w, v.id), beds = w.buildings.filter(b => b.kind === 'home' && b.settlementId === v.id).reduce((s, b) => s + capacity(b), 0);
    return `<button class="settlement-card ${c.focus === v.id ? 'active' : ''}" data-village="${esc(v.id)}" aria-label="${esc(v.name)} 관찰" aria-pressed="${c.focus === v.id}"><b>${esc(v.name)}</b><span>주민 ${people.length} · 주거 ${beds}인</span><span>공동 식량 ${stock.food} · 시장 ${m.food} · 가격 ${m.foodPrice}</span><span>목재 ${stock.wood} · 시장 기금 ${m.coins}</span></button>`;
  }).join('')}</div><div class="civilization-controls"><label for="world-detail">먼 마을의 기록</label><select id="world-detail"><option value="full" ${c.detail === 'full' ? 'selected' : ''}>모든 일상 기록</option><option value="focused" ${c.detail === 'focused' ? 'selected' : ''}>중요 사건 중심</option></select><span>운송·이주 ${c.journeys.length}건 · 자원과 생존 규칙은 동일합니다.</span></div>${c.journeys.length ? `<details><summary>이동 중인 사람과 화물</summary>${c.journeys.map(j => `<p>${esc(c.settlements.find(v => v.id === j.from)!.name)} → ${esc(c.settlements.find(v => v.id === j.to)!.name)} · ${j.kind === 'trade' ? `식량 ${j.food}개 / 대금 ${j.coins}` : j.npcIds.map(id => esc(w.npcs.find(n => n.id === id)!.identity.name)).join(', ')} · ${j.progress}/${j.path.length}칸 <button class="evidence-link" data-event="${esc(j.sourceEventId)}">출발 이유</button></p>`).join('')}</details>` : ''}${urbanView(w)}${heritageView(w)}`;
}
