import type { DynastyView } from '../sim/dynasty';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const num=(n:number)=>n.toLocaleString('ko-KR',{maximumFractionDigits:2});
const person=(p:{id:string;name:string})=>`<button class="text-button" data-biography="${esc(p.id)}">${esc(p.name)}</button>`;
export function familyTree(v:DynastyView,offset=0){
  const people=[...(v.family?.people??[])].sort((a,b)=>a.generation-b.generation||a.id.localeCompare(b.id)),rows=people.slice(offset,offset+60);
  return `<p class="muted">부모 → 자녀 · 배우자는 별도 연결로 표시합니다. 이름을 누르면 생애와 원본 사건을 읽습니다.</p>${rows.map((n,i)=>`${i===0||rows[i-1].generation!==n.generation?`<h4 class="family-generation">${n.generation}세대</h4>`:''}<article class="family-node" data-family-node="${esc(n.id)}"><div class="family-parents">${n.parents.length?n.parents.map(person).join(' + '):'기록된 부모 없음'}<span aria-hidden="true"> ↓</span></div><div class="family-person">${person(n)} <span>${n.age}세 · ${n.alive?'생존':'생애 종료'}</span></div>${n.partner?`<div class="family-partner">배우자 ↔ ${person(n.partner)}</div>`:''}<button class="text-button" data-my-npc="${esc(n.id)}">지도에서 찾기</button>${n.apprenticeship?`<p class="family-learning">${esc(n.apprenticeship.mentorName)}에게 ${esc(n.apprenticeship.label)} 학습 ${n.apprenticeship.lessons}회 · ${n.apprenticeship.choice==='continue'?'가업 진로 선택':n.apprenticeship.choice==='independent'?'다른 진로 선택':'배우는 중'} <button class="text-button" data-event="${esc(n.apprenticeship.source)}">기록</button></p>`:''}</article>`).join('')}<nav class="family-pages" aria-label="가계도 페이지">${offset?`<button class="button" data-family-page="${Math.max(0,offset-60)}">이전</button>`:''}<span>${people.length?offset+1:0}–${Math.min(offset+60,people.length)} / ${people.length}명</span>${offset+60<people.length?`<button class="button" data-family-page="${offset+60}">다음</button>`:''}</nav>`;
}
export function familyDashboard(v:DynastyView,owner:boolean){
  const f=v.family;if(!f)return '';
  return `<section class="family-dashboard"><div class="family-section-heading"><div><span class="eyebrow">ROOTS & BRANCHES</span><h3>우리 가문의 연결</h3></div><button class="button" data-family-map>가문 지도 켜기</button></div><div id="family-tree">${familyTree(v)}</div>
  <section class="family-return"><h3>${v.changes?.since==null?'가문의 최근 발자취':'지난 가문 관찰 이후'}</h3>${v.changes?.coinDelta!=null?`<p>${Math.floor(v.changes.since!/144)+1}일째 이후 생존 가문원 코인 <strong>${v.changes.coinDelta>=0?'+':''}${num(v.changes.coinDelta)}</strong></p><p class="muted">구성원의 출생·사망과 상속·사업·생활 지출이 함께 반영됩니다. 아래 개별 사건에서 기록된 금액과 이유를 확인하세요.</p>`:'<p>다음에 내 가문을 열면 이번 관찰 이후의 변화를 모아 보여줍니다.</p>'}<div class="dynasty-history">${v.changes?.events.map(e=>`<button class="causal-button" data-event="${esc(e.id)}">${Math.floor(e.tick/144)+1}일 · ${esc(e.description)}</button>`).join('')||'<p>이 기간에 기록된 변화가 없습니다.</p>'}</div>${v.changes?.more?'<p class="muted">최근 24건을 표시합니다. 구성원의 생애에서 이전 기록을 이어 볼 수 있습니다.</p>':''}</section>
  <section class="family-businesses"><h3>가문의 사업과 가업</h3><p class="muted">가문 지분과 사업 전체 장부를 구분합니다. 운영금은 개인 코인에 합산하지 않습니다. 매출은 시장에 실제 인도한 생산물의 매입 대금입니다.</p>${f.businesses.map(b=>`<article class="family-business"><div class="family-section-heading"><h4>${esc(b.label)} · 가문 지분 ${num(b.weight*100)}%</h4><button class="button" data-family-building="${esc(b.buildingId)}">사업장 찾기</button></div><p>${esc(b.status)}</p><dl class="business-ledger"><div><dt>인수 대금</dt><dd>${num(b.purchase)}</dd></div><div><dt>투입 운영금</dt><dd>${num(b.capital)}</dd></div><div><dt>현재 운영금</dt><dd>${num(b.cash)}</dd></div><div><dt>누적 매출</dt><dd>${num(b.revenue)}</dd></div><div><dt>원가·수리비</dt><dd>${num(b.costs)}</dd></div><div><dt>생산 임금</dt><dd>${num(b.wages)}</dd></div><div><dt>영업 손익</dt><dd>${num(b.profit)}</dd></div><div><dt>누적 분배</dt><dd>${num(b.dividends)}</dd></div></dl><p class="muted">영업 손익 = 매출 − 원가·수리비 − 생산 임금. 인수 대금 회수와는 다릅니다.</p><details><summary>지분 소유자</summary>${b.owners.map(p=>`<p>${person(p)} ${num(p.weight*100)}%</p>`).join('')}</details><button class="text-button" data-event="${esc(b.source)}">인수 근거</button> · <button class="text-button" data-event="${esc(b.latest)}">최근 사업 기록</button></article>`).join('')||'<p>아직 가문이 소유한 사업체가 없습니다. 부를 우선하는 주민은 생활비와 운영금이 충분하면 자신이 일하는 사업체 인수를 검토합니다.</p>'}
  ${owner&&v.active?.alive?`<form id="dynasty-business"><label>현재 아바타의 사업 인수<select name="enterprise" required ${v.availableBusinesses?.length?'':'disabled'}>${v.availableBusinesses?.map(e=>`<option value="${esc(e.id)}">${esc(e.label)}</option>`).join('')||'<option>인수 가능한 공동 사업체 없음</option>'}</select></label><button class="button" ${v.availableBusinesses?.length&&(v.stats?.activeCoins??0)>=68?'':'disabled'}>인수 제안 적용</button></form><p class="muted">소유자 개입: 인수 24 + 운영금 24코인. 생활비 20코인을 남겨야 하며 건강·나이·이동 상태를 다시 확인합니다.</p>`:''}</section>
  <section class="family-influence"><h3>기여로 이어진 관계</h3><p class="muted">직접 받은 도움·배움과 가까이서 목격한 노동·기부만 기록합니다. 한 주민은 하루 한 번 추가 신뢰를 얻으며, 최근 도움을 준 제안자와의 신뢰가 공동 사업 기부 의향에 영향을 줍니다.</p>${f.influence.map(r=>`<p>${person(r.recipient)} → ${person(r.giver)} · 현재 신뢰 ${num(r.trust)} <button class="text-button" data-event="${esc(r.source)}">도움의 근거</button></p>`).join('')||'<p>아직 기록된 직접 기여 경험이 없습니다.</p>'}</section>
  <section><h3>가문의 집과 생활</h3><div class="family-places">${f.homes.map(h=>`<button class="button" data-family-building="${esc(h.id)}">${esc(h.name)} · ${h.owned?'소유 지분 있음':'거주'} · 거주 가문원 ${h.residents.length}명</button>`).join('')||'<p>현재 연결된 집이 없습니다.</p>'}</div></section></section>`;
}
