import type { WorldState, WorldEvent } from '../sim/types';
import { seasonIndex, SEASONS } from '../sim/heritage';
import { familyTree, HISTORY_LABELS, HISTORY_TOPICS, type HistoryTopic } from '../sim/history';
import { SERVICE_LABELS } from '../sim/urban-types';
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export function heritageView(w: WorldState) {
  const id = w.civilization.focus, h = w.heritage.habitats.find(h => h.settlementId === id), council = w.heritage.councils.find(c => c.settlementId === id);
  if (!h || !council) return '';
  const name = (id: string) => esc(w.civilization.settlements.find(v => v.id === id)?.name ?? id);
  return `<details class="heritage-panel" id="heritage-overview"><summary>자연·공동체·역사 <span>${SEASONS[seasonIndex(w)]} · 가축 ${h.livestock}마리</span></summary><div class="urban-metrics"><span>계절 <b>${SEASONS[seasonIndex(w)]}</b></span><span>토양 <b>${h.soil.toFixed(1)}</b></span><span>목초 <b>${h.pasture.toFixed(1)}</b></span><span>가축 <b>${h.livestock}마리</b></span></div><p>수확은 토양을 소모하고 비와 휴경은 회복을 돕습니다. 가축은 목초·곡물을 먹고 식량을 생산합니다. 겨울에는 작황과 자연 재생이 감소합니다.</p>${h.lastEventId ? `<button class="evidence-link" data-event="${esc(h.lastEventId)}">생태 변화의 근거</button>` : ''}
  <h4>주변의 야생동물</h4>${w.frontier?.impact?.filter(i=>i.settlementId===id).map(i=>`<p>${Math.floor(i.since/144)+1}일째부터 관찰 · 야생 열매 소비 ${i.berries}개 · 미수확 작물 손실 ${i.crops}개 · 울타리 보호 누적 ${i.protectedDays}농장·일</p>`).join('')??''}<p>${(w.frontier?.animals??[]).filter(a=>a.settlementId===id).map(a=>`${a.species==='hare'?'토끼':'사슴'} · (${a.position.x}, ${a.position.y}) · ${a.hunger?'먹이 부족 '+a.hunger+'일':'먹이 확보'}`).join('<br>')||'첫 하루가 지나면 주변 야생동물을 관찰합니다.'}</p>${w.frontier?.habitats.find(h=>h.settlementId===id)?.lastEventId?`<button class="evidence-link" data-event="${esc(w.frontier.habitats.find(h=>h.settlementId===id)!.lastEventId)}">먹이·출생·사망 기록</button>`:''}
  <h4>주민 공동결정</h4><p>3일마다 성인 주민이 건강·가족·직업의 필요에 따라 공공투자에 표를 보탭니다. 동률이면 도로·급수·위생·진료·교육 순서로 결정합니다.</p><label><input id="council-enabled" type="checkbox" ${council.autonomous ? 'checked' : ''}/> 주민이 다음 공공투자를 결정</label><p>${council.groups.map(g => `${{ livelihood: '생계 모임', care: '가족 모임', exchange: '교역 모임' }[g.kind]} ${g.members.length}명 · ${SERVICE_LABELS[g.priority]}`).join('<br>') || '첫 하루가 지나면 주민 집단이 구성됩니다.'}</p>${council.lastEventId ? `<button class="evidence-link" data-event="${esc(council.lastEventId)}">공동결정의 근거</button>` : ''}
  <h4>도시 간 관계</h4>${w.heritage.accords.filter(r => r.from === id || r.to === id).map(r => `<p>${name(r.from)} ↔ ${name(r.to)} · ${{ neutral: '통상', cooperation: '교역 협약', dispute: '자원 분쟁' }[r.status]} · 신뢰 ${r.trust} / 긴장 ${r.tension} · 인도 ${r.deliveries}건 ${r.lastEventId ? `<button class="evidence-link" data-event="${esc(r.lastEventId)}">관계의 근거</button>` : ''}</p>`).join('') || '<p>다른 정착지가 생기면 관계를 관찰할 수 있습니다.</p>'}<p class="muted">협약은 산업 화물 운임을 줄이고, 분쟁은 새 산업 교역을 중단합니다. 이동 중인 화물은 계속 인도됩니다.</p>
  <button id="city-history" class="button">도시 연대기와 원인 보기</button></details>`;
}
export function treeView(w: WorldState, npcId: string) {
  const people = familyTree(w, npcId), names = new Map(w.npcs.map(n => [n.id, n.identity.name]));
  return `<h2>가계도와 재산 계승</h2><p>선택 주민에서 가족 관계 3단계·최대 80명을 표시합니다. 재산은 현재 소유액이며 과거 변화는 사건에서 확인합니다.</p><div class="history-list">${people.sort((a, b) => a.generation - b.generation).map(n => `<article><b>${esc(n.name)}${n.alive ? '' : ' †'}</b> · ${n.generation}세대 · 현재 ${n.wealth}코인<p>부모: ${n.parentIds.map(id => esc(names.get(id) ?? id)).join(', ') || '초기 정착민'} · 배우자: ${esc(names.get(n.partnerId ?? '') ?? '없음')}</p>${n.birthEventId ? `<button class="evidence-link" data-event="${esc(n.birthEventId)}">출생</button>` : ''}${n.deathEventId ? `<button class="evidence-link" data-event="${esc(n.deathEventId)}">사망과 상속</button>` : ''}<button class="text-button" data-person-history="${esc(n.id)}">이 인물의 재산·생애 기록</button></article>`).join('')}</div>`;
}
export interface HistoryPage { comparison?: { first: WorldEvent; last: WorldEvent }; epoch?: string; events: WorldEvent[]; next: number | null; note?: string }
export function historyView(page: HistoryPage, topic: HistoryTopic, remote: boolean, person: boolean, from = '', to = '') {
  const changes = page.comparison && page.comparison.first.id !== page.comparison.last.id ? `<section><h3>기간 내 실제 도시 변화</h3><p>${[['population', '인구'], ['food', '식량'], ['treasury', '예산'], ['sick', '환자']].map(([key, name]) => `${name} ${esc(String(page.comparison!.first.data[key] ?? '기록 없음'))} → ${esc(String(page.comparison!.last.data[key] ?? '기록 없음'))}`).join(' · ')}</p><button class="evidence-link" data-event="${esc(page.comparison.first.id)}">처음 관측</button><button class="evidence-link" data-event="${esc(page.comparison.last.id)}">마지막 관측</button><p class="muted">아래 사건으로 변화의 근거를 살펴보세요. 여러 원인의 기여도를 자동으로 추정하지 않습니다.</p></section>` : '';
  return `<h2>${person ? '인물의 생애와 재산 기록' : '도시 연대기와 원인'}</h2><form id="history-query"><label for="history-topic">관찰할 질문</label><select id="history-topic">${HISTORY_TOPICS.map(t => `<option value="${t}" ${t === topic ? 'selected' : ''}>${HISTORY_LABELS[t]}</option>`).join('')}</select><div class="history-dates"><label>시작 일<input id="history-from" type="number" min="1" value="${esc(from)}"/></label><label>마지막 일<input id="history-to" type="number" min="1" value="${esc(to)}"/></label></div><button class="button">기록 조회</button></form><p class="muted">${esc(page.note ?? '기록에 있는 변화와 원인 링크를 보여줍니다. 시간상 연속된 사건이 반드시 원인과 결과인 것은 아닙니다.')} 이주 이전 기록의 도시 정보가 없으면 인물 기록에서 찾아볼 수 있습니다.</p>${changes}<div class="history-list">${page.events.map(e => `<article><span>${Math.floor(e.tick / 144) + 1}일 · ${esc(e.id)}</span><p>${esc(e.description)}</p><button class="evidence-link" data-event="${esc(e.id)}">원문과 이후 영향</button>${e.causeId ? `<button class="evidence-link" data-event="${esc(e.causeId)}">기록된 원인</button>` : '<small>별도 원인 링크 없음</small>'}</article>`).join('') || '<p>이 조건에 해당하는 기록이 아직 없습니다.</p>'}</div>${page.next !== null ? '<button id="history-more" class="button">이전 역사 40건</button>' : ''}<hr/><h3>AI와 역사 관찰</h3><p>위 기록은 모델 없이도 읽을 수 있습니다. 외부 API 모드에서는 모델이 세계의 최근 실행 근거에서 관련 사건을 고릅니다. 선택한 사건은 서버가 검증하고 원문 링크로 남깁니다.</p>${remote ? '<button id="history-ai" class="button">AI로 최근 세계 근거 선택</button>' : '<p class="muted">Chrome은 기존 목표 선택을 담당합니다. AI 역사 근거 선택은 외부 API를 직접 설정·선택했을 때 사용할 수 있습니다.</p>'}<p class="muted">자유로운 한국어 대화는 별도 품질 검증 대상입니다. 모델의 선택은 사실의 증명이나 새로운 원인 분석이 아닙니다.</p>`;
}
