import type { NeighborView, ObservedGoal } from '../sim/neighbors';
import { TURN_LABELS } from '../sim/relationship-turns';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const num=(n:number)=>n.toLocaleString('ko-KR',{maximumFractionDigits:1});
export function goalCards(goals: ObservedGoal[]) {
  return `<div class="neighbor-goals">${goals.map(g=>`<article class="neighbor-goal ${g.evidence?'achieved':''}" data-goal="${g.id}"><span class="eyebrow">${g.evidence?'달성 기록 있음':'다음 이야기'}</span><h4>${esc(g.title)}</h4><p>${esc(g.condition)}</p>${g.evidence?`<button class="causal-button" data-event="${esc(g.evidence.id)}">${Math.floor(g.evidence.tick/144)+1}일 · ${esc(g.evidence.description)}</button><p class="muted">당시의 달성 기록입니다. 지금의 상태와 다를 수 있습니다.</p>`:`<p class="muted">${esc(g.remaining)}</p>`}</article>`).join('')}</div>`;
}
export function neighborsView(v: NeighborView) {
  const name=(id:string)=>v.people.find(n=>n.id===id)?.name??id;
  return `<section id="neighbors-panel" data-epoch="${esc(v.epoch)}"><span class="eyebrow">FIVE NEIGHBORS, SHARED STORIES</span><h2>내 이웃들의 하루</h2><p>직접 만든 ${v.people.length}명 · 생존 ${v.people.filter(n=>n.alive).length}명. 자녀와 후손은 내 가문에서 이어봅니다.</p>
  <div class="neighbor-toolbar"><button class="button" data-neighbors-refresh>최신 모습 보기</button><button class="button" data-neighbors-dynasty>가문과 사업 목표</button></div>
  ${v.people.length?'':'<div class="empty-state"><p>첫 주민을 만들고 함께 살아갈 이웃을 만나 보세요.</p><button class="button dark" data-dynasty-create>첫 이웃 만들기</button></div>'}
  <div class="neighbor-people">${v.people.map(n=>`<article class="neighbor-person" data-neighbor="${esc(n.id)}"><div class="family-section-heading"><h3>${esc(n.name)}</h3><span>${n.age}세 · ${esc(n.occupation)}</span></div><p>${esc(n.village)} · (${n.position.x}, ${n.position.y})</p><strong>${esc(n.action)}</strong><details class="neighbor-reason"><summary>행동을 고른 이유</summary><p>${esc(n.reason)}</p></details><p class="neighbor-needs ${n.problems.length?'urgent':''}">${n.alive?esc(n.problems.join(' · ')||'급한 생활 문제 없음'):'남겨진 삶의 이야기'}</p><div class="neighbor-toolbar">${n.alive?`<button class="button" data-neighbor-follow="${esc(n.id)}">지도에서 따라가기</button>`:''}<button class="button" data-biography="${esc(n.id)}">생애 기록</button></div></article>`).join('')}</div>
  <h3>우리가 함께 이룰 일</h3><p class="muted">같은 활동에 내 주민 2명 이상이 참여한 실제 결과를 기록합니다. 자원 보상은 없으며 주민이 스스로 선택합니다.</p>${goalCards(v.goals)}
  <h3>서로를 바라보는 지금</h3><p class="muted">화살표는 한 사람이 상대에게 느끼는 관계입니다. 두 방향을 따로 보여줍니다.</p><div class="neighbor-relations">${v.people.flatMap(n=>n.relations.map(r=>`<p><b>${esc(n.name)} → ${esc(name(r.id))}</b><br>친밀 ${num(r.familiarity)} · 신뢰 ${num(r.trust)} · 호감 ${num(r.affection)} · 원망 ${num(r.resentment)}</p>`)).join('')||'<p>아직 서로의 관계 기록이 없습니다.</p>'}</div>
  <h3>관계가 달라진 순간</h3><p class="muted">기록을 시작한 뒤의 변화입니다. 시작 인연을 과거의 만남으로 만들지 않습니다. 같은 방향의 전환 기록은 최소 3일 간격입니다.</p><div class="neighbor-turns">${v.turns.map(e=>`<article><span class="eyebrow">${Math.floor(e.tick/144)+1}일 · ${esc(TURN_LABELS[String(e.data.turn)]??'관계 변화')}</span><h4>${esc(name(e.actorId!))} → ${esc(name(e.targetId!))}</h4><p>${esc(String(e.data.meaning??''))}</p><p>신뢰 ${num(Number(e.data.trustBefore))} → ${num(Number(e.data.trustAfter))} · 호감 ${num(Number(e.data.affectionBefore))} → ${num(Number(e.data.affectionAfter))}<br>원망 ${num(Number(e.data.resentmentBefore))} → ${num(Number(e.data.resentmentAfter))}</p><button class="text-button" data-event="${esc(e.id)}">변화 기록</button>${e.causeId?` · <button class="text-button" data-event="${esc(e.causeId)}">원인이 된 사건</button>`:''}</article>`).join('')||'<p>아직 기록된 관계 전환이 없습니다. 만남과 도움, 갈등이 쌓이는 모습을 지켜보세요.</p>'}</div>${v.next!==null?'<button class="button" data-neighbors-older>이전 순간 더 보기</button>':''}
  <p class="muted">${Math.floor(v.tick/144)+1}일째 조회. 최신 모습 보기를 누르면 갱신합니다.</p><p id="neighbors-status" role="status"></p></section>`;
}
