import { livingWorldView } from './living';
import { HOMES } from '../sim/living-types';
import type { WorldState, NPC } from '../sim/types';
import { city, cityMetrics } from '../sim/urban';
import { GOODS, SERVICES, GOOD_LABELS, INDUSTRY_LABELS, SERVICE_LABELS } from '../sim/urban-types';
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
const num = (n: number) => Math.round(n).toLocaleString('ko-KR');
let layer = 'population';
let district = 'all';
export function setUrbanLayer(value: string) { if (['population', 'food', 'jobs', 'health'].includes(value)) layer = value; }
export function setDistrict(value: string) { if (['all', 'nw', 'ne', 'sw', 'se'].includes(value)) district = value; }
export function citizenView(w: WorldState, n: NPC) {
  const u = w.urban.citizens[n.id]; if (!u) return '';
  const e = w.urban.enterprises.find(e => e.id === u.employer), household = w.npcs.filter(p => p.alive && p.homeId === n.homeId);
  return `<div class="family-card"><div class="section-label">도시에서의 생활</div><p>일자리: ${e ? esc(INDUSTRY_LABELS[e.kind]) + ` · 작업당 ${e.wage}코인` : n.identity.age < 18 ? '성장·교육' : '자영 생계 활동'}<br>교육 ${num(u.education)} · 영양 ${num(u.nutrition)} · 스트레스 ${num(u.stress)}<br>주거 만족 ${num(u.housing)} · 행정 신뢰 ${num(u.trust)}<br>질병 ${num(u.disease)} · 부상 ${num(u.injury)}<br>당일 임금·거래·운송·임대 수입 ${u.income} / 구매·세금·임대 지출 ${u.expenses}</p><p>직업 숙련: ${Object.entries(u.skills).map(([k, v]) => `${INDUSTRY_LABELS[k as keyof typeof u.skills]} ${num(v)}`).join(' · ')}</p><p>동거 ${household.length}명 · 아동 ${household.filter(p => p.identity.age < 18).length}명 · 가족 식량 ${household.reduce((s, p) => s + p.inventory.food, 0)}개 · 재산 ${household.reduce((s, p) => s + p.wealth, 0)}코인</p></div>`;
}
export function urbanView(w: WorldState) {
  if (!w.urban) return '';
  const id = w.civilization.focus, v = w.civilization.settlements.find(v => v.id === id)!, c = city(w, id), m = cityMetrics(w, id);
  const enterprises = w.urban.enterprises.filter(e => e.settlementId === id);
  const buildings = w.buildings.filter(b => b.settlementId === id && (district === 'all' || (b.position.y < v.center.y ? 'n' : 's') + (b.position.x < v.center.x ? 'w' : 'e') === district));
  const samples = w.urban.samples.filter(s => s.settlementId === id).slice(-30), max = Math.max(1, ...samples.map(s => s.population));
  const points = samples.map((s, i) => `${8 + i * 284 / Math.max(1, samples.length - 1)},${72 - s.population / max * 60}`).join(' ');
  return `${livingWorldView(w)}<details class="urban-panel" id="urban-overview"><summary>지역·도시 관측 <span>${esc(v.name)} · ${m.stage} · ${m.population}명</span></summary>
  <div class="urban-toolbar"><label for="urban-layer">지역 지도</label><select id="urban-layer">${[['population', '인구'], ['food', '식량'], ['jobs', '빈 일자리'], ['health', '질병']].map(([value, name]) => `<option value="${value}" ${layer === value ? 'selected' : ''}>${name}</option>`).join('')}</select><span>지역 선택 → 도시 선택 → 구역·건물 확인</span></div>
  <div class="urban-atlas" aria-label="지역 지도">${w.civilization.settlements.map(v => { const x = cityMetrics(w, v.id), value = layer === 'food' ? x.food : layer === 'jobs' ? x.jobs : layer === 'health' ? x.sick : x.population; return `<button data-village="${esc(v.id)}" class="${v.id === id ? 'active' : ''}" style="grid-column:${Math.floor(v.center.x / 32) + 1};grid-row:${Math.floor(v.center.y / 24) + 1}"><b>${esc(v.name)}</b><span>${x.stage} · ${num(value)}</span></button>`; }).join('')}</div>
  <div class="urban-metrics"><span>빈 주거 <b>${m.vacant}인</b></span><span>사업체 고용 <b>${m.employed}/${m.adults} 성인</b></span><span>공공예산 <b>${num(c.treasury)}</b></span><span>행정 신뢰 <b>${num(m.trust)}</b></span><span>비옥도 <b>${c.fertility}</b></span><span>오염 <b>${num(c.pollution)}</b></span></div>
  <p class="muted">사업체 미고용 주민도 기존 농업·채집·거래를 합니다. 도시 승격은 주민 150명·사업체 4개·급수 시설 확보 시 표시됩니다.</p>
  <div class="urban-columns"><section><h4>생산망과 유한 자원</h4><p>곡물 → 가공식품 / 광석 + 목재 → 도구 → 수확량 증가</p><p>${GOODS.map(g => `${GOOD_LABELS[g]} <b>${num(c.goods[g])}</b>`).join(' · ')}<br>남은 매장량: 석재 ${num(c.deposits.stone)} · 광석 ${num(c.deposits.ore)}</p>${enterprises.length ? enterprises.map(e => `<p><b>${INDUSTRY_LABELS[e.kind]}</b> · 고용 ${e.workers.length}/${e.capacity} · 누적 생산 ${e.output} · 내구도 ${num(w.urban.buildings[e.buildingId].condition)} ${e.sourceEventId ? `<button class="evidence-link" data-event="${esc(e.sourceEventId)}">설립 근거</button>` : ''}</p>`).join('') : '<p>공동 목재와 인구 여건에 따라 사업체가 생깁니다.</p>'}</section>
  <section><h4>행정과 공공서비스</h4><p>누적 세입 ${num(c.collected)} · 누적 지출 ${num(c.spent)}</p>${SERVICES.map(s => `<p>${SERVICE_LABELS[s]} · 시설 ${c.services[s]} / 가동 ${c.active[s]}단계</p>`).join('')}<form id="urban-policy"><label for="urban-tax">성인 재산세율 (생활비 10코인 공제)</label><input id="urban-tax" type="number" min="0" max="30" step="1" value="${c.taxRate}" required/><label for="urban-priority">다음 공공투자</label><select id="urban-priority">${SERVICES.map(s => `<option value="${s}" ${c.priority === s ? 'selected' : ''}>${SERVICE_LABELS[s]}</option>`).join('')}</select><button class="button" type="submit">정책 적용</button><p class="muted">정책 변경은 세계의 사건에 기록됩니다. 예산·재료·성인 노동자가 있어야 시설을 건설하고 운영합니다.</p></form></section></div>
  <h4>도시 비교</h4><div class="urban-table"><table><thead><tr><th>정착지</th><th>인구</th><th>빈 주거</th><th>고용</th><th>식량</th><th>환자</th><th>예산</th></tr></thead><tbody>${w.civilization.settlements.map(v => { const m = cityMetrics(w, v.id); return `<tr><td>${esc(v.name)}</td><td>${m.population}</td><td>${m.vacant}</td><td>${m.employed}</td><td>${m.food}</td><td>${m.sick}</td><td>${city(w, v.id).treasury}</td></tr>`; }).join('')}</tbody></table></div>
  <h4>최근 인구 변화</h4>${samples.length > 1 ? `<svg viewBox="0 0 300 86" class="urban-chart" role="img" aria-label="최근 ${samples.length}일 인구 ${samples[0].population}명에서 ${samples.at(-1)!.population}명"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="2"/><text x="8" y="84">${samples[0].population}명 → ${samples.at(-1)!.population}명 · ${samples.length}개 일별 관측</text></svg>` : '<p>하루 이상 진행하면 실제 인구 표본이 표시됩니다.</p>'}
  <h4>구역과 건물</h4><label for="urban-district">도시 구역</label><select id="urban-district">${[['all', '전체'], ['nw', '북서'], ['ne', '북동'], ['sw', '남서'], ['se', '남동']].map(([key, name]) => `<option value="${key}" ${district === key ? 'selected' : ''}>${name}</option>`).join('')}</select><div class="urban-buildings">${buildings.map(b => `<span title="위치 ${b.position.x},${b.position.y}"><b>${esc(b.name)}${b.kind === 'home' ? ` · ${HOMES[w.living.homes[b.id]].label}` : ''}</b><small>${b.position.x}, ${b.position.y} · 내구도 ${num(w.urban.buildings[b.id]?.condition ?? 100)} · 유지비 ${w.urban.buildings[b.id]?.maintenance ?? 0}</small></span>`).join('')}</div>
  <h4>지역 간 공급망</h4>${w.urban.freight.length ? w.urban.freight.map(f => `<p>${esc(w.civilization.settlements.find(v => v.id === f.from)!.name)} → ${esc(w.civilization.settlements.find(v => v.id === f.to)!.name)} · ${GOOD_LABELS[f.good]} ${f.amount}개 · 운임 ${f.fee} · ${f.progress}/${f.path.length}칸 <button class="evidence-link" data-event="${esc(f.sourceEventId)}">운송 근거</button></p>`).join('') : '<p>재고 차이와 구매 기금이 있을 때 지역 간 운송이 시작됩니다.</p>'}
  ${c.lastEventId ? `<button class="evidence-link" data-event="${esc(c.lastEventId)}">도시 변화의 최근 근거</button>` : ''}</details>`;
}
